[platformio]
default_envs = esp32dev

; Env for ESP32
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 115200
monitor_speed = 115200

upload_port = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART

monitor_filters = 
    send_on_enter
    debug

lib_deps = 
	nrf24/RF24 @ ^1.4.11

; To test on my computer
[env:native]
platform = native
build_flags = -std=c++17
test_build_src = true    ; 👈 Force la compilation des fichiers sources dans src/
build_src_filter = 
    +<*> 
    -<main.cpp>
    -<hal/esp32/*>