[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200
upload_port = /dev/cu.SLAB_USBtoUART

monitor_filters = 
    send_on_enter
    debug